import Head from 'next/head'
import PageFormat from '../Components/PageFormat/PageFormat'

export default function ProductsPage() {
  return (
    <>
      <Head>
        <title>Vestis | Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageFormat>
        <p>Yo</p>
      </PageFormat>
    </>
  )
}
